"""
Local Book Forge — Pipeline Chain
------------------------------------
Chains all three pipeline stages into one run, matching the intended order:

    writer + cover art (local-book-generator.py)
        -> editor pass (editorial_agent.py, --auto-apply by default)
        -> scorer + Finished Product Notes.txt (scoring_agent.py)

Built as a standalone script deliberately separate from dashboard_server.py /
dashboard.html — it doesn't modify either of those, so it can't affect
whatever is currently running through the dashboard UI while this was
developed. Not wired into the dashboard's "Run" button yet; that's a
follow-up step (see phase-2-roadmap.md, section 3, item 7) once this has
been tried standalone and that is signed off. Until then, run it
directly from a terminal exactly like the other three scripts.

Usage:
    Generate a brand-new book and chain it all the way through
    (writer -> cover -> editor -> scorer):
        python pipeline_chain.py
        python pipeline_chain.py --genre "sci-fi thriller"

    Chain an already-generated book straight to editor + scorer
    (skips Stage A/B/C — use this to catch up books made before this
    script existed, or ones generated by hand through the dashboard):
        python pipeline_chain.py --book-dir "output_books\\your-book-folder"

    Suggest-only editing instead of the chain's default --auto-apply
    (matches editorial_agent.py's own safer standalone default, in case
    you want to review edits before they're written to edited/ — note
    this means the scorer will fall back to scoring the raw draft, since
    there's no edited/ version yet):
        python pipeline_chain.py --suggest-only

Must be run from the `files` folder, same as the other three scripts
(paths to local-book-generator.py / editorial_agent.py / scoring_agent.py
are resolved relative to this script's own location, not cwd, so it also
works if invoked with a full path from elsewhere).

Exit code is 0 only if every stage that ran completed successfully — useful
for future batch/dashboard wiring to detect a failed book without parsing
output text.
"""

import argparse
import os
import subprocess
import sys
import time

# Same UTF-8 console reconfigure as the other three scripts — Windows'
# default console codepage can't encode some of the unicode this pipeline's
# output uses (curly quotes, arrows, etc.).
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", line_buffering=True)
    sys.stderr.reconfigure(encoding="utf-8", line_buffering=True)
try:
    sys.stdout.reconfigure(line_buffering=True, encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(line_buffering=True, encoding="utf-8", errors="replace")
except AttributeError:
    pass  # Python < 3.7 fallback, not expected here

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_ROOT = os.path.join(SCRIPT_DIR, "output_books")

GENRE_POOL = [
    "sci-fi thriller",
    "cozy mystery",
    "epic fantasy",
    "romantic suspense",
    "psychological horror",
    "dystopian survival",
    "noir detective",
    "space opera",
]

# =====================================================================
# 1. CLI
# =====================================================================

parser = argparse.ArgumentParser(
    description="Chain local-book-generator.py -> editorial_agent.py -> scoring_agent.py "
                "into one run."
)
parser.add_argument(
    "--book-dir",
    default=None,
    help="Skip generation and chain editor + scorer onto an already-generated "
         "output_books/<slug-timestamp> folder. Omit to generate a brand-new book first.",
)
parser.add_argument(
    "--genre",
    choices=GENRE_POOL,
    default=None,
    help="Genre to write, only used when generating a new book (--book-dir omitted). "
         "Omit for a random pick, same as local-book-generator.py's own default.",
)
parser.add_argument(
    "--suggest-only",
    action="store_true",
    help="Run the editor in suggest-only mode (no --auto-apply) instead of the chain's "
         "default of trusting auto-apply. The scorer will then fall back to the raw draft, "
         "since no edited/ version will exist.",
)
parser.add_argument(
    "--writer-model",
    default=None,
    help="Forwarded straight to local-book-generator.py's own --writer-model (dashboard "
         "section 6.12), to A/B test an alternate writer model through the full chain. Only "
         "used when generating a new book (--book-dir omitted) — ignored otherwise, since no "
         "writer stage runs in that path.",
)
parser.add_argument(
    "--separate-passes",
    action="store_true",
    help="Forwarded to editorial_agent.py — use its original three separate review calls per "
         "chapter instead of the single combined pass. Roughly 3x slower through the editor "
         "stage.",
)
# Book Structure passthrough (dashboard's Book Structure panel). These only
# apply when generating a new book — with --book-dir the writer stage doesn't run.
# Defined as a group so adding one later means touching a single list.
STRUCTURE_ARGS = [
    ("--min-chapters", int, "Minimum chapter count asked of the outline model."),
    ("--max-chapters", int, "Maximum chapter count."),
    ("--min-total-words", int, "Whole-book word floor."),
    ("--max-total-words", int, "Whole-book word ceiling."),
    ("--min-chapter-words", int, "Per-chapter target floor."),
    ("--max-chapter-words", int, "Per-chapter target ceiling."),
]
for _flag, _type, _help in STRUCTURE_ARGS:
    parser.add_argument(_flag, type=_type, default=None,
                        help=f"{_help} Forwarded to local-book-generator.py.")

parser.add_argument(
    "--cooldown",
    type=int,
    default=20,
    help="Seconds to pause between stages so the finished stage's VRAM/RAM is actually released "
         "before the next one starts (default: 20). After the pause, the chain additionally "
         "waits for free VRAM to come back above a working threshold. Set 0 to disable the "
         "fixed pause — the VRAM check still runs.",
)
parser.add_argument(
    "--python-exe",
    default=sys.executable,
    help="Python interpreter to launch each stage with. Defaults to the interpreter "
         "running this script (matches dashboard_config.json's python_exe on the reference setup).",
)
args = parser.parse_args()

LOCAL_BOOK_GENERATOR = os.path.join(SCRIPT_DIR, "local-book-generator.py")
EDITORIAL_AGENT = os.path.join(SCRIPT_DIR, "editorial_agent.py")
SCORING_AGENT = os.path.join(SCRIPT_DIR, "scoring_agent.py")

# =====================================================================
# 2. STAGE RUNNER — subprocess with live-streamed output, same shape as
#    dashboard_server.py's Job._run (unbuffered, stdout+stderr merged, line
#    by line) but printed straight to this process's own console instead of
#    pushed into a queue, since this is a standalone CLI tool, not the
#    Flask server. A [stage] prefix on every line keeps a 3-stage chain's
#    combined output easy to scan.
# =====================================================================


def get_free_vram_mb() -> "int | None":
    """Query free VRAM in MB via nvidia-smi. Same helper as the three pipeline
    scripts — duplicated per this codebase's standalone-script convention."""
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=memory.free", "--format=csv,noheader,nounits"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0 and result.stdout.strip():
            return int(result.stdout.strip().splitlines()[0])
    except (subprocess.SubprocessError, FileNotFoundError, ValueError, OSError):
        pass
    return None


def cooldown(seconds: int, target_vram_mb: int = 6000) -> None:
    """Pause between stages so the finished stage's resources are actually
    released before the next one starts claiming them. Added 2026-08-13.

    A subprocess exiting is not the same as its GPU memory being free: the
    CUDA context teardown and the driver-side reclaim both lag process exit by
    a few seconds, and Ollama's server process (which outlives the Python
    script that called it) only drops a model when it's told to or when
    keep_alive expires. Starting the next stage into that window is how a run
    ends up with two models' worth of allocation on an 8GB card, which Ollama
    resolves by silently falling back to CPU rather than erroring.

    Waits out a fixed settle period, then blocks until VRAM actually comes back
    (up to a cap) rather than trusting the fixed pause alone."""
    print(f"\n[pipeline] Cooldown: waiting {seconds}s for the previous stage to fully release "
          f"its resources...")
    time.sleep(seconds)
    free = get_free_vram_mb()
    if free is None:
        return  # no nvidia-smi to gate on; the fixed pause is all we have
    waited = 0
    while free is not None and free < target_vram_mb and waited < 60:
        if waited == 0:
            print(f"[pipeline] Only {free}MB VRAM free (want {target_vram_mb}MB) — waiting for "
                  f"it to clear before starting the next stage.")
        time.sleep(2)
        waited += 2
        free = get_free_vram_mb()
    if free is not None:
        if free >= target_vram_mb:
            print(f"[pipeline] {free}MB VRAM free — starting next stage.")
        else:
            print(f"[WARN] Still only {free}MB VRAM free after waiting. Starting the next stage "
                  f"anyway, but it may be slow — check for a leftover A1111 or ollama process.")


def run_stage(label: str, cmd: list) -> int:
    print(f"\n{'=' * 70}")
    print(f"[pipeline] Starting stage: {label}")
    print(f"[pipeline] $ {' '.join(cmd)}")
    print(f"{'=' * 70}\n")
    process = subprocess.Popen(
        cmd,
        cwd=SCRIPT_DIR,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        bufsize=1,
    )
    for line in process.stdout:
        print(f"[{label}] {line.rstrip(chr(10))}")
    process.wait()
    status = "OK" if process.returncode == 0 else f"FAILED (exit {process.returncode})"
    print(f"\n[pipeline] Stage '{label}' finished: {status}")
    return process.returncode


# =====================================================================
# 3. BOOK-DIR DETECTION — after Stage A/B/C runs, find the folder it just
#    created. Same "most recently modified subfolder with an outline.json"
#    heuristic already used by editorial_agent.py / scoring_agent.py, but
#    additionally requires the folder to be newer than this run's own start
#    time — a generation run that crashed before writing outline.json must
#    not silently fall through to re-processing an older, unrelated book.
# =====================================================================


def find_new_book_dir(output_root: str, not_before: float) -> "str | None":
    if not os.path.isdir(output_root):
        return None
    candidates = [
        os.path.join(output_root, name)
        for name in os.listdir(output_root)
        if os.path.isdir(os.path.join(output_root, name))
        and os.path.isfile(os.path.join(output_root, name, "outline.json"))
    ]
    candidates = [c for c in candidates if os.path.getmtime(c) >= not_before]
    if not candidates:
        return None
    candidates.sort(key=os.path.getmtime, reverse=True)
    return candidates[0]


# =====================================================================
# 4. MAIN — sequential chain, matching the pipeline order exactly. No stage
#    runs concurrently with another (VRAM on the reference 8GB 4060 doesn't allow
#    it — local-book-generator.py already handles the Ollama<->A1111 handoff
#    internally for its own Stage B/C; editor and scorer are Ollama-only and
#    run as separate sequential processes here, so there's no additional
#    VRAM coordination needed between them beyond simply not overlapping).
# =====================================================================

book_dir = args.book_dir

if book_dir is None:
    for script, label in ((LOCAL_BOOK_GENERATOR, "local-book-generator.py"),):
        if not os.path.isfile(script):
            print(f"[ERROR] Could not find {label} at '{script}'.")
            sys.exit(1)

    gen_cmd = [args.python_exe, "-u", LOCAL_BOOK_GENERATOR]
    if args.genre:
        gen_cmd += ["--genre", args.genre]
    if args.writer_model:
        gen_cmd += ["--writer-model", args.writer_model]
    for _flag, _type, _help in STRUCTURE_ARGS:
        _value = getattr(args, _flag.lstrip("-").replace("-", "_"))
        if _value is not None:
            gen_cmd += [_flag, str(_value)]

    start_time = time.time()
    rc = run_stage("writer+cover", gen_cmd)
    if rc != 0:
        print("[pipeline] Book generation failed — stopping chain before editor/scorer.")
        sys.exit(rc)

    book_dir = find_new_book_dir(OUTPUT_ROOT, start_time)
    if not book_dir:
        print(
            "[pipeline] Book generation reported success, but no new output_books/ folder "
            "with an outline.json was found — stopping chain rather than guessing which "
            "book to edit/score."
        )
        sys.exit(1)
    print(f"[pipeline] New book folder: {book_dir}")
else:
    if not os.path.isdir(book_dir) or not os.path.isfile(os.path.join(book_dir, "outline.json")):
        print(f"[ERROR] --book-dir '{book_dir}' doesn't look like a book folder (no outline.json).")
        sys.exit(1)
    if args.writer_model:
        print(f"[pipeline] Note: --writer-model '{args.writer_model}' is ignored with --book-dir — "
              f"no writer stage runs when chaining onto an already-generated book.")
    print(f"[pipeline] Chaining editor + scorer onto existing book folder: {book_dir}")

overall_rc = 0

editor_cmd = [args.python_exe, "-u", EDITORIAL_AGENT, "--book-dir", book_dir]
if not args.suggest_only:
    editor_cmd.append("--auto-apply")
if args.separate_passes:
    editor_cmd.append("--separate-passes")
cooldown(args.cooldown)
rc = run_stage("editor", editor_cmd)
if rc != 0:
    overall_rc = rc
    print("[pipeline] Editor stage failed — continuing to scorer anyway so a score/"
          "notes still gets produced (scoring_agent.py degrades to the raw draft on its own "
          "if no edited/ version exists).")

scorer_cmd = [args.python_exe, "-u", SCORING_AGENT, "--book-dir", book_dir]
cooldown(args.cooldown)
rc = run_stage("scorer", scorer_cmd)
if rc != 0:
    overall_rc = rc

print(f"\n{'=' * 70}")
print("PIPELINE CHAIN COMPLETE")
print(f"{'=' * 70}")
print(f"Book folder: {book_dir}")
print(f"Overall result: {'ALL STAGES OK' if overall_rc == 0 else 'ONE OR MORE STAGES FAILED — see output above'}")

score_report = os.path.join(book_dir, "book_score_report.txt")
notes_file = os.path.join(book_dir, "Finished Product Notes.txt")
if os.path.isfile(score_report):
    print(f"Score report: {score_report}")
if os.path.isfile(notes_file):
    print(f"Finished Product Notes: {notes_file}")

sys.exit(overall_rc)
